version: '3.7'

services:

  elasticsearch:

    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2

    container_name: elasticsearch

    environment:

      - node.name=elasticsearch

      - cluster.name=es-docker-cluster

      - bootstrap.memory_lock=true

      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"

      - discovery.type=single-node

    ulimits:

      memlock:

        soft: -1

        hard: -1

    volumes:

      - es-data:/usr/share/elasticsearch/data

    ports:

      - 9200:9200

    networks:

      - elastic

  kibana:

    image: docker.elastic.co/kibana/kibana:7.10.2

    container_name: kibana

    environment:

      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

    ports:

      - 5601:5601

    networks:

      - elastic

    depends_on:

      - elasticsearch

volumes:

  es-data:

    driver: local

networks:

  elastic:

    driver: bridge
